name: Test CommScores
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Pip, pytest, commscores
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install commscores
          pip show commscores
      - name: Run tests
        run: python -m pytest test\test_commscores.py